Add Validation with Cmake 3.14
deepmodeling/deepflame-dev pull request #63
Opened 2022-09-27 06:33 UTC by JX278

2022-09-27 09:56 UTC, caic99 reviewed
Why there is a space in filename [.github/workflows/build_test .yml](https://github.com/deepmodeling/deepflame-dev/pull/63/files/8f114ef5f86fc5ef7576a593b7a9d33b2e5a0d14..5bec1d97b0b91f85d80476c801514ec7de0033cf#diff-5ed1e04b87ad888c40761177b4d8c1ba114d604db341240fa59a75d3ed31c8ae)?

2022-09-27 11:12 UTC, caic99 requested changes

2022-09-27 11:12 UTC, caic99 commented on .github/workflows/Test.yml
> +        apt-get install -y sudo wget unzip git software-properties-common make cmake g++ mpich openmpi-bin libopenmpi-dev libscalapack-mpi-dev
Please pay attention to the usage of `--no-install-recommends`.
```suggestion
        apt-get update 
        apt-get install -y --no-install-recommends sudo wget unzip git software-properties-common make cmake g++ mpich openmpi-bin libopenmpi-dev libscalapack-mpi-dev 
```

2022-09-27 11:16 UTC, JX278 commented
> Why there is a space in filename [.github/workflows/build_test .yml](https://github.com/deepmodeling/deepflame-dev/pull/63/files/8f114ef5f86fc5ef7576a593b7a9d33b2e5a0d14..5bec1d97b0b91f85d80476c801514ec7de0033cf#diff-5ed1e04b87ad888c40761177b4d8c1ba114d604db341240fa59a75d3ed31c8ae)?

It's now modified to a version without the space.

2022-09-29 06:20 UTC, zhixchen commented
Is this PR still a work-in-progress?

2022-09-30 03:45 UTC, JX278 commented
> Is this PR still a work-in-progress?

It's now done. The validation of 2D TGV is changed to compare the maximum temperature in the y direction.

2022-09-30 07:08 UTC, zhixchen approved these changes

2022-09-30 07:55 UTC, merged