add diffusion velocity correction and timing function for dfHighSpeedFoam, correct alpha in rhoEEqn.H and clean the code
deepmodeling/deepflame-dev pull request #9
Opened 2022-07-11 06:26 UTC by pkuLmq

2022-07-17 04:13 UTC, zhixchen commented
Can we still keep the "invisid" option?

2022-07-17 04:17 UTC, zhixchen commented
This is to resolve issue #1

2022-07-17 11:52 UTC, OpenFOAMFans approved these changes

2022-07-19 03:16 UTC, zhixchen requested changes
The diffusion correction should be included in the "!invisid" condition.

2022-07-20 07:03 UTC, zhixchen approved these changes

2022-07-20 07:05 UTC, zhixchen commented on applications/solvers/dfHighSpeedFoam/rhoEEqn.H
> +         - fvc::laplacian(turbulence->alphaEff()*thermo.gamma(), e)
FVM is compatiable with the current energy definition. This is to be further investigated in a future version.

2022-07-20 07:05 UTC, merged